# Generated by Django 4.2 on 2023-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0002_delete_accessory_delete_accessorycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(default='Default Order Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
