# Generated by Django 4.2 on 2023-05-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0005_alter_order_order_name_alter_order_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(),
        ),
    ]
