# Generated by Django 4.2 on 2023-05-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0007_alter_order_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_quantity',
        ),
    ]
