# Generated by Django 4.2 on 2023-05-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0008_remove_order_order_name_remove_order_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_product_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
