# Generated by Django 4.2 on 2023-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0009_order_order_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_product_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
