# Generated by Django 4.2 on 2023-05-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0010_rename_order_product_name_order_name_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
