# Generated by Django 4.2 on 2023-05-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0011_remove_order_name_remove_order_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cell_City.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cell_City.product')),
            ],
        ),
    ]
