# Generated by Django 4.2 on 2023-05-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0012_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
