# Generated by Django 4.2 on 2023-06-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0016_remove_address_street_address_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
