# Generated by Django 4.2 on 2023-06-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0019_alter_productreview_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
