# Generated by Django 4.2 on 2023-06-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0021_order_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
