# Generated by Django 4.2 on 2023-06-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0022_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
