# Generated by Django 4.2 on 2023-06-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0030_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cell_City.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cell_City.product')),
            ],
        ),
    ]
