# Generated by Django 4.2.1 on 2023-06-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0031_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
