# Generated by Django 4.2 on 2023-06-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0034_remove_feedback_user_feedback_email_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cell_City.product'),
            preserve_default=False,
        ),
    ]
