# Generated by Django 4.2 on 2023-06-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cell_City', '0038_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default='Asia/Kolkata'),
        ),
    ]
